apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eiffeltower
    version: 0.0.1
    env: dev
  name: eiffeltower
  namespace: 1-eiffeltower
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: eiffeltower
  strategy: {}
  template:
    metadata:
      labels:
        app: eiffeltower
        version: 0.0.1
    spec:
      containers:
        - name: app
          image:  chmadhus/eiffel-tower
          imagePullPolicy: Always
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "20m"