apiVersion: v1
kind: Service
metadata:
  labels:
    app: eiffeltower
  name: eiffeltower-service
  namespace: 1-eiffeltower
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: eiffeltower
    version: 0.0.1
  type: NodePort