apiVersion: v1
kind: Service
metadata:
  name: {{ include "sitemaintenance.fullname" . }}
  labels:
    {{- include "sitemaintenance.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}      
      protocol: TCP      
  selector:
    {{- include "sitemaintenance.selectorLabels" . | nindent 4 }}
