## Global Docker image parameters
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

replicaCount: 1


image:  
  repository: sitemaintenance/master
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
      
service:
  type: ClusterIP
  port: 80

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# values.yaml
message: ""
headline: ""
teamName: ""
title: ""
